modLoader="javafml"
loaderVersion="[32,)"
license="${license}"
issueTrackerURL="https://github.com/vakiliner/ChatComponentAPI/issues"

[[mods]]
modId="chatcomponentapi"
version="${version}"
displayName="ChatComponentAPI"
authors="VAKiliner"
description='''
ChatComponentAPI для ChatModerator
'''
displayURL="https://github.com/vakiliner/ChatComponentAPI"
updateJSONURL="https://raw.githubusercontent.com/vakiliner/ChatComponentAPI/refs/heads/main/update.json"

[[dependencies.chatcomponentapi]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16,1.17)"
